export const docsNavGroups = [
  {
    title: "Getting Started",
    links: [
      { name: "Introduction", href: "/ui-docs" },
      { name: "Decorations", href: "/ui-docs/decorations" },
    ],
  },
  {
    title: "Cards & Layouts",
    links: [
      { name: "Card (Base API)", href: "/ui-docs/cards" },
      { name: "E-Commerce Cards", href: "/ui-docs/cards-ecommerce" },
      { name: "Editorial & Blog Cards", href: "/ui-docs/cards-editorial" },
      { name: "Event & Ticket Cards", href: "/ui-docs/cards-event" },
      { name: "User Profile Cards", href: "/ui-docs/cards-profile" },
    ],
  },
  {
    title: "Atoms",
    links: [
      { name: "Typography", href: "/ui-docs/typography" },
      { name: "Buttons", href: "/ui-docs/buttons" },
      { name: "Combobox", href: "/ui-docs/combobox" },
      { name: "Badges", href: "/ui-docs/badges" },
      { name: "Avatars", href: "/ui-docs/avatars" },
      { name: "Input", href: "/ui-docs/inputs" },
      { name: "Label", href: "/ui-docs/labels" },
      { name: "Checkbox", href: "/ui-docs/checkbox" },
      { name: "Switch", href: "/ui-docs/switch" },
      { name: "Slider", href: "/ui-docs/slider" },
      { name: "Progress", href: "/ui-docs/progress" },
      { name: "Textarea", href: "/ui-docs/textarea" },
      { name: "Radio", href: "/ui-docs/radio-group" },
      { name: "Toggle", href: "/ui-docs/toggle" },
      { name: "Aspect Ratio", href: "/ui-docs/aspect-ratio" },
    ],
  },
  {
    title: "Molecules",
    links: [
      { name: "Alert", href: "/ui-docs/alert" },
      { name: "Breadcrumb", href: "/ui-docs/breadcrumb" },
      { name: "Calendar", href: "/ui-docs/calendar" },
      { name: "Form", href: "/ui-docs/form" },
      { name: "Collapsible", href: "/ui-docs/collapsible" },
      { name: "Date Picker", href: "/ui-docs/date-picker" },
      { name: "Table", href: "/ui-docs/table" },
      { name: "Data Table", href: "/ui-docs/data-table" },
      { name: "Chart", href: "/ui-docs/chart" },
      { name: "Stepper", href: "/ui-docs/stepper" },
      { name: "Tabs", href: "/ui-docs/tabs" },
      { name: "Hover Card", href: "/ui-docs/hover-card" },
      { name: "Popover", href: "/ui-docs/popover" },
      { name: "Select", href: "/ui-docs/select" },
      { name: "Scroll Area", href: "/ui-docs/scroll-area" },
      { name: "Separator", href: "/ui-docs/separator" },
      { name: "Skeleton", href: "/ui-docs/skeleton" },
      { name: "Tooltip", href: "/ui-docs/tooltip" },
    ],
  },
  {
    title: "Organisms",
    links: [
      { name: "Accordion", href: "/ui-docs/accordion" },
      { name: "Carousel", href: "/ui-docs/carousel" },
      { name: "Drawer", href: "/ui-docs/drawer" },
      { name: "Alert Dialog", href: "/ui-docs/alert-dialog" },
      { name: "Context Menu", href: "/ui-docs/context-menu" },
      { name: "Dialog", href: "/ui-docs/dialog" },
      { name: "File Upload", href: "/ui-docs/file-upload" },
      { name: "Input OTP", href: "/ui-docs/input-otp" },
      { name: "Command", href: "/ui-docs/command" },
      { name: "Pagination", href: "/ui-docs/pagination" },
      { name: "Navigation Menu", href: "/ui-docs/navigation-menu" },
      { name: "Sortable List", href: "/ui-docs/sortable-list" },
      { name: "Menubar", href: "/ui-docs/menubar" },
      { name: "Resizable", href: "/ui-docs/resizable" },
      { name: "Sheet", href: "/ui-docs/sheet" },
      { name: "Sonner", href: "/ui-docs/sonner" },
    ],
  },
];
